#!/bin/sh
mkdir -p tools
cd tools

if [ ! -e "sbt-launch.jar" ]
then
  wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.1/sbt-launch.jar	
  if [ ! -s "sbt-launch.jar" ]
  then
    echo >&2 "ERROR: Could not download SBT"
    exit 1
  fi  
fi
	
cd ..

java -Xms256M -Xmx512M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -jar tools/sbt-launch.jar run
