#!/bin/bash
mkdir tools
cd tools

if [ ! -e "sbt-launch.jar" ]
then
 wget http://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-launch//0.12.1/sbt-launch.jar	
fi
	
cd ..

java -Xms256M -Xmx512M -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=384M -jar tools/sbt-launch.jar run
